# Redirect all traffic from Netlify subdomain to custom domain
[[redirects]]
  from = "https://texttoownhandwriting.netlify.app/*"
  to = "https://texttohandwriting.asmitphuyal.com.np/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://texttoownhandwriting.netlify.app/*"
  to = "https://texttohandwriting.asmitphuyal.com.np/:splat"
  status = 301
  force = true